elk_ip='192.168.10.248:9200/'
all = "*"
where_id_param = "where id={}"
directory_id = "directory_id"
tags = "tags"
workflow_id="workflow_id"
created_date = "created_date"
modified_date = 'modified_date'
modified_by_id = 'modified_by_id'
created_by_id = 'created_by_id'
tag_dir_rel = 'file_manager_directory_tags'
tag_id = "tag_id"
field = "field"
label = "label"
name="name"
owner_id = 'owner_id'
token="token"
user="user"
request="request"
username="username"

Name="Name"
Workflow="Workflow"
tags="tags"
id="id"
user_id="user_id"
directory_id="directory_id"
directory="Directory"
file="file"
user_name="user_name"
file_manager_tag="file_manager_tag"
id_name="id,name"
where_id_in ="where id in"
where_id ="where id ="
added_tag="added_tag"
deleted_tag="deleted_tag"
new_tag_ids="new_tag_ids"
old_tag_ids="old_tag_ids"
new_tag="new_tag"
parent_id_key="parent_id"
shared_dirs_key="shared_dirs"
file_ids="file_ids"
file_id="file_id"
sub_directories="sub_directories"
Files_Serializer="Files:: Serializer{}"
share_invlid="share is invlid"
Added="Added"
Tag="Tag"
tag="tag"
action="action"
Removed="Removed"
get="get"
child_dirs="child-dirs"
Dictionary_get_child_dirs="Dictionary:: get_child_dirs: Child Object {}"
parent_dirs="parent-dirs"
Files_get_parent_dir="Files:: get_parent_dirs: Parent Files{}"
error="error"
shared_dirs="shared-dirs"
file_manager="file_manager"
get_shared_dirs="get_shared_dirs"
file_manager_share_user_ids="file_manager_share_user_ids"
status="status"
No_Directories="No Directories"
put="put"
post="post"
shared_ids = "shared_ids"
share="share"
upload="upload"
file="file"
file_type="file_type"
size="size"
file_content_type="file_content_type"
null="null"
where_id="where id="
Tags="Tags"
Deleted="Deleted"
File_Removed="File Removed"
parent_files="parent-files"
where_directory_id_is="where directory_id is null and owner_id = {0}"
shared_files="shared-files"
get_shared_files="get_shared_files"
file_manager_share_user_ids="file_manager_share_user_ids"
No_Files="No Files"
download="download"
uploads="uploads/{}"
Content_Disposition="Content-Disposition"
attachment_filename= 'attachment; filename="{}"'
edit="edit"
contents="contents"
edit_pdfconvert="edit_pdfconvert"
download_path='/home/next/Downloads/hj.pdf'
Done="Done"
related_files="related-files"
where_owner_id="where owner_id = "
url_mytasks="mytasks"
Info_request="Info {} \n request: {}"
file_key="File"

delete_tag_query="delete_tag_query"
parent_id="where parent_id is null and owner_id={} order by name"
deletedFile="deletedFile"
file_manager_file="file_manager_file"
file_related_field_query="file_related_field_query"
can_read="can_read"
read="read"
can_write='can_write'
write='write'
can_delete='can_delete'
delete="delete"



strUAMLink ="http://192.168.10.236:8000"
strAppName = "DMS"
strAppClient = "DMS_Admin"
