Created="Created"
all="*"
Updated="Updated"
created_by_id="created_by_id"
owner_id="owner_id"
created_date="created_date"
user_id="user_id"
modified_date="modified_date"
modified_by_id="modified_by_id"
field="field"
directory_id="directory_id"
id="id"
Generating_log="Generating log"
label="label"
Create_message="Create message"
Log_id_not_found="Log id not found"
symmetric="symmetric"
actvity_update="actvity update"
Track_fields_not_match="Track fields not match"
Added="Added"
tag="tag"
action="action"
share="share"
name="name"
Removed="Removed"
Workflow="Workflow"
directiory="Directory"
workflow_id="workflow_id"
has_been_changed_from ="has been changed from "
message="message"
where="where "
where_id="where id={0}"
Data_before_update_not_awailable="Data before updat e not awailable"
Parametter_missing="Parametter missing"
activity_time="activity_time"
log_id="log_id"
created_by_id="created_by_id"
error="error"
activity_url="activity/(?P<activity_id>[0-9]+)"
type="type"
dir="dir"
file="file"
file_id="file_id"
file_key="File"
put="put"
auth_user="auth_user"
group_ids="group_ids"
user_ids="user_ids"
first_name="first_name"
last_name="last_name"
share_user_msg="is shared to user - "
share_group_msg="is shared to group - "

with_key="with"
auth_group="auth_group"
permissions="permissions"
version="version"
POST="POST"
auth_url="http://127.0.0.1:8000/api-token-auth/"
utf8="utf-8"
username="username"
password="password"
transform_url='http://192.168.10.61/check?user_name='
msg="msg"
info="info"
success="success"
content_type="content-type"
application_json='application/json'
email="email"
where_email="where email='{}'"
version="version"
HTTP_HOST="HTTP_HOST"
api_token_auth="/api-token-auth/"
status="status"



